// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ampkv.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_ampkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ampkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ampkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_ampkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

type SetWithTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWithTTLRequest) Reset() {
	*x = SetWithTTLRequest{}
	mi := &file_ampkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWithTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithTTLRequest) ProtoMessage() {}

func (x *SetWithTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithTTLRequest.ProtoReflect.Descriptor instead.
func (*SetWithTTLRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{4}
}

func (x *SetWithTTLRequest) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *SetWithTTLRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_ampkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_ampkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{6}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ampkv_proto protoreflect.FileDescriptor

const file_ampkv_proto_rawDesc = "" +
	"\n" +
	"\vampkv.proto\x12\x05ampkv\"F\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"D\n" +
	"\vGetResponse\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\n" +
	"SetRequest\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\"U\n" +
	"\x11SetWithTTLRequest\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xec\x01\n" +
	"\fAmpKVService\x12,\n" +
	"\x03Get\x12\x11.ampkv.GetRequest\x1a\x12.ampkv.GetResponse\x122\n" +
	"\x03Set\x12\x11.ampkv.SetRequest\x1a\x18.ampkv.OperationResponse\x12@\n" +
	"\n" +
	"SetWithTTL\x12\x18.ampkv.SetWithTTLRequest\x1a\x18.ampkv.OperationResponse\x128\n" +
	"\x06Delete\x12\x14.ampkv.DeleteRequest\x1a\x18.ampkv.OperationResponseB)Z'github.com/Unfield/AmpKV/pkg/client/rpcb\x06proto3"

var (
	file_ampkv_proto_rawDescOnce sync.Once
	file_ampkv_proto_rawDescData []byte
)

func file_ampkv_proto_rawDescGZIP() []byte {
	file_ampkv_proto_rawDescOnce.Do(func() {
		file_ampkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ampkv_proto_rawDesc), len(file_ampkv_proto_rawDesc)))
	})
	return file_ampkv_proto_rawDescData
}

var file_ampkv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ampkv_proto_goTypes = []any{
	(*KeyValue)(nil),          // 0: ampkv.KeyValue
	(*GetRequest)(nil),        // 1: ampkv.GetRequest
	(*GetResponse)(nil),       // 2: ampkv.GetResponse
	(*SetRequest)(nil),        // 3: ampkv.SetRequest
	(*SetWithTTLRequest)(nil), // 4: ampkv.SetWithTTLRequest
	(*DeleteRequest)(nil),     // 5: ampkv.DeleteRequest
	(*OperationResponse)(nil), // 6: ampkv.OperationResponse
}
var file_ampkv_proto_depIdxs = []int32{
	0, // 0: ampkv.GetResponse.kv:type_name -> ampkv.KeyValue
	0, // 1: ampkv.SetRequest.kv:type_name -> ampkv.KeyValue
	0, // 2: ampkv.SetWithTTLRequest.kv:type_name -> ampkv.KeyValue
	1, // 3: ampkv.AmpKVService.Get:input_type -> ampkv.GetRequest
	3, // 4: ampkv.AmpKVService.Set:input_type -> ampkv.SetRequest
	4, // 5: ampkv.AmpKVService.SetWithTTL:input_type -> ampkv.SetWithTTLRequest
	5, // 6: ampkv.AmpKVService.Delete:input_type -> ampkv.DeleteRequest
	2, // 7: ampkv.AmpKVService.Get:output_type -> ampkv.GetResponse
	6, // 8: ampkv.AmpKVService.Set:output_type -> ampkv.OperationResponse
	6, // 9: ampkv.AmpKVService.SetWithTTL:output_type -> ampkv.OperationResponse
	6, // 10: ampkv.AmpKVService.Delete:output_type -> ampkv.OperationResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ampkv_proto_init() }
func file_ampkv_proto_init() {
	if File_ampkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ampkv_proto_rawDesc), len(file_ampkv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ampkv_proto_goTypes,
		DependencyIndexes: file_ampkv_proto_depIdxs,
		MessageInfos:      file_ampkv_proto_msgTypes,
	}.Build()
	File_ampkv_proto = out.File
	file_ampkv_proto_goTypes = nil
	file_ampkv_proto_depIdxs = nil
}
