// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: ampkv.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AmpKVDataTypeProto int32

const (
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_UNKNOWN AmpKVDataTypeProto = 0
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_STRING  AmpKVDataTypeProto = 1
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_INT     AmpKVDataTypeProto = 2
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_FLOAT   AmpKVDataTypeProto = 3
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_BOOL    AmpKVDataTypeProto = 4
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_JSON    AmpKVDataTypeProto = 5
	AmpKVDataTypeProto_AMP_KV_DATA_TYPE_BINARY  AmpKVDataTypeProto = 6
)

// Enum value maps for AmpKVDataTypeProto.
var (
	AmpKVDataTypeProto_name = map[int32]string{
		0: "AMP_KV_DATA_TYPE_UNKNOWN",
		1: "AMP_KV_DATA_TYPE_STRING",
		2: "AMP_KV_DATA_TYPE_INT",
		3: "AMP_KV_DATA_TYPE_FLOAT",
		4: "AMP_KV_DATA_TYPE_BOOL",
		5: "AMP_KV_DATA_TYPE_JSON",
		6: "AMP_KV_DATA_TYPE_BINARY",
	}
	AmpKVDataTypeProto_value = map[string]int32{
		"AMP_KV_DATA_TYPE_UNKNOWN": 0,
		"AMP_KV_DATA_TYPE_STRING":  1,
		"AMP_KV_DATA_TYPE_INT":     2,
		"AMP_KV_DATA_TYPE_FLOAT":   3,
		"AMP_KV_DATA_TYPE_BOOL":    4,
		"AMP_KV_DATA_TYPE_JSON":    5,
		"AMP_KV_DATA_TYPE_BINARY":  6,
	}
)

func (x AmpKVDataTypeProto) Enum() *AmpKVDataTypeProto {
	p := new(AmpKVDataTypeProto)
	*p = x
	return p
}

func (x AmpKVDataTypeProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmpKVDataTypeProto) Descriptor() protoreflect.EnumDescriptor {
	return file_ampkv_proto_enumTypes[0].Descriptor()
}

func (AmpKVDataTypeProto) Type() protoreflect.EnumType {
	return &file_ampkv_proto_enumTypes[0]
}

func (x AmpKVDataTypeProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmpKVDataTypeProto.Descriptor instead.
func (AmpKVDataTypeProto) EnumDescriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{0}
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          AmpKVDataTypeProto     `protobuf:"varint,3,opt,name=type,proto3,enum=ampkv.AmpKVDataTypeProto" json:"type,omitempty"`
	Cost          int64                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_ampkv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetType() AmpKVDataTypeProto {
	if x != nil {
		return x.Type
	}
	return AmpKVDataTypeProto_AMP_KV_DATA_TYPE_UNKNOWN
}

func (x *KeyValue) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ampkv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ampkv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_ampkv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

type SetWithTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            *KeyValue              `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWithTTLRequest) Reset() {
	*x = SetWithTTLRequest{}
	mi := &file_ampkv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWithTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithTTLRequest) ProtoMessage() {}

func (x *SetWithTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithTTLRequest.ProtoReflect.Descriptor instead.
func (*SetWithTTLRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{4}
}

func (x *SetWithTTLRequest) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *SetWithTTLRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_ampkv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_ampkv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampkv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_ampkv_proto_rawDescGZIP(), []int{6}
}

func (x *OperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ampkv_proto protoreflect.FileDescriptor

const file_ampkv_proto_rawDesc = "" +
	"\n" +
	"\vampkv.proto\x12\x05ampkv\"u\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.ampkv.AmpKVDataTypeProtoR\x04type\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x03R\x04cost\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"D\n" +
	"\vGetResponse\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\n" +
	"SetRequest\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\"U\n" +
	"\x11SetWithTTLRequest\x12\x1f\n" +
	"\x02kv\x18\x01 \x01(\v2\x0f.ampkv.KeyValueR\x02kv\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xd8\x01\n" +
	"\x12AmpKVDataTypeProto\x12\x1c\n" +
	"\x18AMP_KV_DATA_TYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17AMP_KV_DATA_TYPE_STRING\x10\x01\x12\x18\n" +
	"\x14AMP_KV_DATA_TYPE_INT\x10\x02\x12\x1a\n" +
	"\x16AMP_KV_DATA_TYPE_FLOAT\x10\x03\x12\x19\n" +
	"\x15AMP_KV_DATA_TYPE_BOOL\x10\x04\x12\x19\n" +
	"\x15AMP_KV_DATA_TYPE_JSON\x10\x05\x12\x1b\n" +
	"\x17AMP_KV_DATA_TYPE_BINARY\x10\x062\xec\x01\n" +
	"\fAmpKVService\x12,\n" +
	"\x03Get\x12\x11.ampkv.GetRequest\x1a\x12.ampkv.GetResponse\x122\n" +
	"\x03Set\x12\x11.ampkv.SetRequest\x1a\x18.ampkv.OperationResponse\x12@\n" +
	"\n" +
	"SetWithTTL\x12\x18.ampkv.SetWithTTLRequest\x1a\x18.ampkv.OperationResponse\x128\n" +
	"\x06Delete\x12\x14.ampkv.DeleteRequest\x1a\x18.ampkv.OperationResponseB)Z'github.com/Unfield/AmpKV/pkg/client/rpcb\x06proto3"

var (
	file_ampkv_proto_rawDescOnce sync.Once
	file_ampkv_proto_rawDescData []byte
)

func file_ampkv_proto_rawDescGZIP() []byte {
	file_ampkv_proto_rawDescOnce.Do(func() {
		file_ampkv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ampkv_proto_rawDesc), len(file_ampkv_proto_rawDesc)))
	})
	return file_ampkv_proto_rawDescData
}

var file_ampkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ampkv_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ampkv_proto_goTypes = []any{
	(AmpKVDataTypeProto)(0),   // 0: ampkv.AmpKVDataTypeProto
	(*KeyValue)(nil),          // 1: ampkv.KeyValue
	(*GetRequest)(nil),        // 2: ampkv.GetRequest
	(*GetResponse)(nil),       // 3: ampkv.GetResponse
	(*SetRequest)(nil),        // 4: ampkv.SetRequest
	(*SetWithTTLRequest)(nil), // 5: ampkv.SetWithTTLRequest
	(*DeleteRequest)(nil),     // 6: ampkv.DeleteRequest
	(*OperationResponse)(nil), // 7: ampkv.OperationResponse
}
var file_ampkv_proto_depIdxs = []int32{
	0, // 0: ampkv.KeyValue.type:type_name -> ampkv.AmpKVDataTypeProto
	1, // 1: ampkv.GetResponse.kv:type_name -> ampkv.KeyValue
	1, // 2: ampkv.SetRequest.kv:type_name -> ampkv.KeyValue
	1, // 3: ampkv.SetWithTTLRequest.kv:type_name -> ampkv.KeyValue
	2, // 4: ampkv.AmpKVService.Get:input_type -> ampkv.GetRequest
	4, // 5: ampkv.AmpKVService.Set:input_type -> ampkv.SetRequest
	5, // 6: ampkv.AmpKVService.SetWithTTL:input_type -> ampkv.SetWithTTLRequest
	6, // 7: ampkv.AmpKVService.Delete:input_type -> ampkv.DeleteRequest
	3, // 8: ampkv.AmpKVService.Get:output_type -> ampkv.GetResponse
	7, // 9: ampkv.AmpKVService.Set:output_type -> ampkv.OperationResponse
	7, // 10: ampkv.AmpKVService.SetWithTTL:output_type -> ampkv.OperationResponse
	7, // 11: ampkv.AmpKVService.Delete:output_type -> ampkv.OperationResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ampkv_proto_init() }
func file_ampkv_proto_init() {
	if File_ampkv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ampkv_proto_rawDesc), len(file_ampkv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ampkv_proto_goTypes,
		DependencyIndexes: file_ampkv_proto_depIdxs,
		EnumInfos:         file_ampkv_proto_enumTypes,
		MessageInfos:      file_ampkv_proto_msgTypes,
	}.Build()
	File_ampkv_proto = out.File
	file_ampkv_proto_goTypes = nil
	file_ampkv_proto_depIdxs = nil
}
