// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: ampkv.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AmpKVService_Get_FullMethodName        = "/ampkv.AmpKVService/Get"
	AmpKVService_Set_FullMethodName        = "/ampkv.AmpKVService/Set"
	AmpKVService_SetWithTTL_FullMethodName = "/ampkv.AmpKVService/SetWithTTL"
	AmpKVService_Delete_FullMethodName     = "/ampkv.AmpKVService/Delete"
)

// AmpKVServiceClient is the client API for AmpKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmpKVServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	SetWithTTL(ctx context.Context, in *SetWithTTLRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*OperationResponse, error)
}

type ampKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAmpKVServiceClient(cc grpc.ClientConnInterface) AmpKVServiceClient {
	return &ampKVServiceClient{cc}
}

func (c *ampKVServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, AmpKVService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ampKVServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, AmpKVService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ampKVServiceClient) SetWithTTL(ctx context.Context, in *SetWithTTLRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, AmpKVService_SetWithTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ampKVServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationResponse)
	err := c.cc.Invoke(ctx, AmpKVService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmpKVServiceServer is the server API for AmpKVService service.
// All implementations must embed UnimplementedAmpKVServiceServer
// for forward compatibility.
type AmpKVServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*OperationResponse, error)
	SetWithTTL(context.Context, *SetWithTTLRequest) (*OperationResponse, error)
	Delete(context.Context, *DeleteRequest) (*OperationResponse, error)
	mustEmbedUnimplementedAmpKVServiceServer()
}

// UnimplementedAmpKVServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAmpKVServiceServer struct{}

func (UnimplementedAmpKVServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAmpKVServiceServer) Set(context.Context, *SetRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedAmpKVServiceServer) SetWithTTL(context.Context, *SetWithTTLRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWithTTL not implemented")
}
func (UnimplementedAmpKVServiceServer) Delete(context.Context, *DeleteRequest) (*OperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAmpKVServiceServer) mustEmbedUnimplementedAmpKVServiceServer() {}
func (UnimplementedAmpKVServiceServer) testEmbeddedByValue()                      {}

// UnsafeAmpKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmpKVServiceServer will
// result in compilation errors.
type UnsafeAmpKVServiceServer interface {
	mustEmbedUnimplementedAmpKVServiceServer()
}

func RegisterAmpKVServiceServer(s grpc.ServiceRegistrar, srv AmpKVServiceServer) {
	// If the following call pancis, it indicates UnimplementedAmpKVServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AmpKVService_ServiceDesc, srv)
}

func _AmpKVService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmpKVServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmpKVService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmpKVServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmpKVService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmpKVServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmpKVService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmpKVServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmpKVService_SetWithTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWithTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmpKVServiceServer).SetWithTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmpKVService_SetWithTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmpKVServiceServer).SetWithTTL(ctx, req.(*SetWithTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmpKVService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmpKVServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AmpKVService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmpKVServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AmpKVService_ServiceDesc is the grpc.ServiceDesc for AmpKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AmpKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ampkv.AmpKVService",
	HandlerType: (*AmpKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AmpKVService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _AmpKVService_Set_Handler,
		},
		{
			MethodName: "SetWithTTL",
			Handler:    _AmpKVService_SetWithTTL_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AmpKVService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ampkv.proto",
}
